### ISSUE TITLE
Resource Characterization

### ISSUE THREAD

**Issue by Engineer1119** [spacedecentral/Coral#21]
How will the mining equipment be able to characterize the material it extracts?
For example, in a given scoop of loose regolith (if that´s what we are mining), how will we determine: 
What kinds of resources are present?
In what chemical forms are they present?
In what physical forms are they present?
How are they distributed across the surface?

**Comment by Engineer1119** [comment]
[Here ](https://docs.google.com/spreadsheets/d/1bkHw_ekMEbXps_7yKP-LLcbINslKgCAeYVVvDBRmCXI/edit#gid=0) is a partial database of material properties of interest

**Comment by timallard** [comment]
For elemental iron I've only found reference to "microscopic" particles no density/volume figures yet on mare soils.

**Comment by jrcgarry** [comment]
<nods>
My understanding is that its thought to be present (primarily) as a nanophase, condensed from meteoritic impact processes.
<modest justification for that belief here>

Page 3:
http://www.isruinfo.com/docs/the_lunar_dust_problem_-_from_liability_to_asset.pdf

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
