### ISSUE TITLE
Literature review on Thermal Management

### ISSUE THREAD

**Issue by Engineer1119** [spacedecentral/Coral#25]
Research the different technologies,  strategies or materials for efficient thermal management for surviving the harsh days and nights of the Moon, including new technologies and systems that are likely to be used on commercial space vehicles. Consider the possibility of surviving a lunar night.

List each technology by the following factors:

Approximate Level of Maturity on a 1-to-10 TRL scale
Approximate Level of Complexity on a 1-to-10 point scale, 1 being the least, 10 being the most.
Approximate Level of Reliability on a 1-to-10 point scale, 1 being the least, 10 being the most.
Approximate Cost Impact on a 1-to-10 point scale, 1 being the least, 10 being the most.
Approximate Availability in the Marketplace on a 1-to-10 point scale, 1 being the least, 10 being the most.
Particular benefits of each technology.
Particular detriments of each technology.
Category (Active or Passive) 

Document these results above here: https://docs.google.com/spreadsheets/d/199wz-e5hkhjWGHNJFy-9Gf2A8XoLlf8l2PIlLoFVSCY/edit#gid=0

Also, any source material for the listed factors above needs to be retained in the research documentation for peer review purposes. It is understood that some of the factors may be educated guesses or outright assumptions from the outset of the research phase, and all factors will be fully vetted during the peer review process for validity and accuracy.

Good source to begin: 
https://www.nasa.gov/sites/default/files/atoms/files/2015_nasa_technology_roadmaps_ta_14_thermal_management_final.pdf

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
