### ISSUE TITLE
Assembly Hardware

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#26]
Identify and research the different components needed for assembling structures, such as robotic arms, cranes, printing heads, etc.
Research areas include existing industrial processes, cutting-edge hardware, and everything in between. Research should consider how manufacturing processes influence the ease and efficiency of assembly.

**Comment by founder-outbound** [comment]
I have an intense desire to help on this task. Design is my baseline skill.

**Comment by Suzibianco** [comment]
Hey Craig, this is great!
This task is still in a definition stage, and will be part of a working group later on. But you can begin researching! Please open up a subfolder in the google drive [TBO](https://drive.google.com/drive/folders/10P_UcQ34iZ-9PBl6CWYXjORbEdqsWKvB?ogsrc=32) folder for your findings. Once we have the working groups sorted out, we will know where to store it permanently.

**Comment by Suzibianco** [comment]
Hey @founder-outbound, I'm closing this task because we won't really be doing the structural assembly. But you can still work on the assembly of the system, printer, etc right?

**Comment by founder-outbound** [comment]
Certainly!
