### ISSUE TITLE
Literature review on Mobility (Guidance, Navigation, & Control)

### ISSUE THREAD

**Issue by Engineer1119** [spacedecentral/Coral#31]
The vehicle hardware and the software that controls it.
Note: Coral will be a payload on a 3rd party vehicle. Research should focus on available, in-progress, and rumored vehicles that may operate on the lunar surface.

**Comment by timallard** [comment]
Dealing with the dust, is 2 track monorail on T's considered for tonnage and keeping vehicles above affecting the dust, seeing the ref to 3rd party, this to do distance on terrain single vehicle vs the speed
& capacity of monorail?

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
