### ISSUE TITLE
Compile research into a spreadsheet (Moon, regolith, 3D printing papers)

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#33]
Create a Google spreadsheet listing (and linking) the papers found, their authors, keywords, main subject, relevance to Coral, the status of the research, summary of results and other pertinent information.

**Comment by founder-outbound** [comment]
I would be happy to collect and organize this information.

**Comment by Suzibianco** [comment]
Great Craig! This is an organization task, dependent on the research task "[Literature review on key Coral topics: Moon, regolith, 3D printing](https://github.com/spacedecentral/coral/issues/36)". So it might take a while before there's much to organize.
You can begin by checking out our [proto-wiki](https://drive.google.com/drive/folders/1AB5cbHr8RqisjpuU8uWroTczjzrJU5Yj?ogsrc=32) to sort the documents we already have in there. Please save this spreadsheet in the Wiki folder.

**Comment by Suzibianco** [comment]
@founder-outbound, as we talked last week, this task is no longer needed because each person who researches something will be responsible for documenting that research in a spreadsheet.
