### ISSUE TITLE
Provide your thoughts on the Coral mission

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#41]
How to complete this task:

1.  Create a new issue (issues are tasks). The title of the new issue should be "My thoughts - name " where name is your name.
2.  In the body of the issue, add a reference to this issue  (e.g., "This issue is in response to #41")
3.  Move your issue to the "In progress" column. This is to assure you will get assigned points for this task.
4.  Write a 2-3 paragraph essay on your thoughts in relation to Coral. try to answer the following:

- What do you envision when you think about the Coral Mission?
- What are some of your expectations for this mission?
- How do you think we will achieve the long-term objective of building a habitat on the moon?
- If you had to describe a concept for the entire mission right now, what would it be?

5. Please place your document in [this folder]

(https://drive.google.com/drive/folders/1hrcON9dMOrLtYwJhgslnBvT7cnDvPPce?usp=sharing) in our shared google drive.

**Comment by timallard** [comment]
Two short pages, underground living, to deal with dust rails for transport, using algae purification of wastewater to remove CO2, produce oxygen, use the oils and algae mass for products, i.e. lubes, soaps.
Recalling Biosphere 3 for the need tovl remove CO2, sequestration isn't enough.
https://drive.google.com/folderview?id=16oAE-1rn5a8DdtFp4nbwP1Mx8kKXXNnY

**Comment by Suzibianco** [comment]
Awesome @timallard, can you put this in a folder with your name in our shared drive, more specifically [here](https://drive.google.com/drive/folders/1hrcON9dMOrLtYwJhgslnBvT7cnDvPPce?usp=sharing)?
