### ISSUE TITLE
Provide your thoughts on the Coral mission - Tom Mallard

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#43]
This task is for @timallard's response to #41 

@timallard Please add the documents you shared with me to this folder: https://drive.google.com/drive/folders/1hrcON9dMOrLtYwJhgslnBvT7cnDvPPce?usp=sharing

**Comment by timallard** [comment]
![notebook_tho_ts_page16](https://user-images.githubusercontent.com/546520/43555131-44fa7f14-95ad-11e8-9541-f7209069fd2f.png)
![notebook_tho_ts_page17](https://user-images.githubusercontent.com/546520/43555161-705bb95c-95ad-11e8-9a75-bfcad68b6759.png)

Suzi, let me know if these don't work, had a chore getting them to devices.

**Comment by Suzibianco** [comment]
Hey @timallard, I meant put them in the google drive folder: https://drive.google.com/drive/folders/1hrcON9dMOrLtYwJhgslnBvT7cnDvPPce?usp=sharing

They did show up hete though! And thank you for the illustration concept!

**Comment by timallard** [comment]
I forgot, algae oils can be used as crude oil now to supply plastics and other products.

**Comment by timallard** [comment]
Excavation, the dirt likely has horizontal very fine layers of ejecta events, impact or volcanic the thought to focus collection on these as less volume to process, i.e. sensing metals for tool guidance the idea first, overturning overburden vs digging for gauging total volume moved for it.

**Comment by timallard** [comment]
New vision: Satisfy all requirements in demo if not needed to produce pigmented glass cloisonnais 3D coins microprinted with the patch design as product: https://drive.google.com/file/d/1Y2x67w-WPNFNW6UYFpsou9sGDCvCGseU/view?usp=drivesdk
