### ISSUE TITLE
My thoughts on the Coral mission - Erik Kulu

### ISSUE THREAD

**Issue by erikkulu** [spacedecentral/Coral#46]
This issue is in response to #41

(@erikkulu I edited this because my instructions post was pointing this to the wrong reference issue)

**Comment by Suzibianco** [comment]
Great Erik, please place your response in this Google Doc folder: https://drive.google.com/drive/folders/1hrcON9dMOrLtYwJhgslnBvT7cnDvPPce?usp=sharing

**Comment by erikkulu** [comment]
Added
