### ISSUE TITLE
Trade studies - our spacecraft

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#63]
What kind of spacecraft do we want to create? A multi-purpose, all-in-one rover that is able to mine, process and print? An assembly-line-type system consisting of separate equipment for each function? Something that moves around by itself? A stationary equipment with auxiliary robots? If we need a rover, are we using someone else´s or making our own?

In order to define this, we need to conduct trade studies of the different general characteristics and capabilities of our spacecraft, listing the advantages and disadvantages of each, as well as the feasibility of each in relation to our constraints.

**Comment by capsulecorplab** [comment]
An [objectives tree](https://pmdprostarter.org/objective-tree/) may help with this
