### ISSUE TITLE
Mission Statements + Mission Objectives

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#67]
**Description:**
Identify the Mission Statements and Mission Objectives

**Definition of Task:**
What: Unlike requirements, which specify numerical levels of performance, the mission objectives are broad statements of what the system must do to be useful. These objectives are used to identify the top-level mission requirements (see step 1 of SMAD).

**Lead:**
Andy Gonzales

SMAD template: https://gist.github.com/capsulecorplab/09ca6c698b889821f5ca0c9d26e0db99#file-space_mission_firesat-yaml

**Comment by uditkumarsahoo** [comment]
Hi Suzi, Is this something that I can take up to work on?

**Comment by Suzibianco** [comment]
Yes you can @uditkumarsahoo. We have already started it but you can further develop it. You can also get in contact with Andy Gonzalez and discuss it over with him, since he's taken the lead on this issue. Here's the doc we initiated: https://docs.google.com/document/d/1cXFNPS5QxJUWfEFc_MEW9dnZXRXjbeBCzAE8WGCfr3Y/edit

**Comment by founder-outbound** [comment]
Initial Task Definition document here:
https://docs.google.com/document/d/15i0ELU81nQbteFZ4T7YP7KZBzELF0vvyIHXhlJozgeA/edit#heading=h.r7u6tnk8pst0

**Comment by uditkumarsahoo** [comment]
Project cancelled.
