### ISSUE TITLE
Create templates for documents

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#73]
Create templates for general google drive documents, such as:

- [ ] Literature review

- [ ] Spreadsheets

- [ ] List

**Comment by timallard** [comment]
Suggested titles for watts/gram & eval sheet: https://drive.google.com/file/d/1Od8wngRp-JH9OleVIVrvfKbTod6pCD_u/view?usp=drivesdk

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
