### ISSUE TITLE
Define hosted payload

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#80]
Research the exact meaning of "hosted payload" and if it applies to our use cases.

**Comment by Engineer1119** [comment]
According to the [U.S. Department of Commerce, Office of Space Commerce](https://www.space.commerce.gov/category/government-business/hosted-payloads/): "The term “hosted payloads” refers to the utilization of available capacity on commercial satellites to accommodate additional transponders, instruments, or other spacebound items. By “hitchhiking” on commercial spacecraft already scheduled for launch, government agencies can send sensors and other equipment into space on a timely and cost-effective basis.

The National Space Transportation Policy directs federal agencies to actively explore hosted payloads and other ride-sharing arrangements when planning space missions."

How's this for a definition, and which document needed this question answered?
