### ISSUE TITLE
Research solar concentration techniques

### ISSUE THREAD

**Issue by Engineer1119** [spacedecentral/Coral#85]
At the team meeting on August 27th, we discussed possibly using solar concentrators to apply heat to collected regolith as part of the manufacturing process (in contrast to using electricity derived from solar PV). Research on this topic seeks to answer questions such as:

- has this been done before on Earth? If so, how?
- what are the best and worst cases for using this technique (and how would that be measured)?
- how would this impact payload design (e.g. mass, volume, deployment mechanisms, etc.)?

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
