### ISSUE TITLE
Literature review on Electric Arc sintering

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#87]
Research Electric Arc sintering, its applications, power requirements, overall equipment mass/dimensions, any special requirements?

**Comment by jrcgarry** [comment]
:|
Striking an arc between two extant electrodes and feeding regolith through the arc, with the liquid (boiling, mind) melt as the building block?
:|

There'll be some interesting EMI challenges!
<whooee - fun for whoever picks this up!>

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
