### ISSUE TITLE
Coral library maintenance

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/Coral#95]
Clean up the coral library folder and the index according to the following guidelines:

- Inspect each item in the sub-folders, make sure they are correctly registered in the Index, and fill out any missing information.
- Make sure items are stored in the most relevant sub-folder, which should correspond to the "Category" column in the index.
- Make sure all links in the index correspond to the _**file**_ stored in the drive sub-folder. The only external links should be for web tools, sites or files that need purchasing in order to download.
- Delete duplicate documents and/or entries.

Links:
- [Library drive folder](https://drive.google.com/drive/folders/1AB5cbHr8RqisjpuU8uWroTczjzrJU5Yj)
- [Library Index](https://docs.google.com/spreadsheets/d/1tPZTxwczJXB993BYltIe9KM0xPmZpe8Y5-fuSCEU3j0/edit#gid=2098822104)
- [Library Readme](https://docs.google.com/document/d/1AnNDoKmPaFPClb1gjdkhvOeBKvlnR3ANgYbTcRU_GcY/edit)

Ps: make this a "monthly" task - each month the task re-opened for the specific month

**Comment by Engineer1119** [comment]
note: let's constrain this to one month in scope and open a new one each month

**Comment by cagonzalez8** [comment]
As per advice @timallard naming system (i,e. eng...)

**Comment by Engineer1119** [comment]
considering this to be completed by my start-of-year reorganization of the Drive. Will open new issues at end of each month from here on out.
